name: "✨ Feature Request"
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["Type: Enhancement"]
body:
  - type: markdown
    attributes:
      value: "## ✨ Feature Request\nDescribe the feature or improvement."

  - type: textarea
    id: feature_description
    attributes:
      label: "🚀 Description"
      description: "What would you like to see?"
      placeholder: "I want to add..."

  - type: textarea
    id: use_case
    attributes:
      label: "💡 Use Case"
      description: "Why would this be useful?"
      placeholder: "This feature helps because..."
